# Generated by Django 5.2.3 on 2025-07-02 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkyVoiceLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=30)),
                ('receiver_gender', models.CharField(max_length=10)),
                ('receiver_age', models.PositiveIntegerField()),
                ('receiver_type', models.CharField(max_length=30)),
                ('receiver_special_note', models.CharField(blank=True, max_length=100)),
                ('content_text', models.TextField(blank=True)),
                ('voice_file', models.FileField(blank=True, null=True, upload_to='skyvoice/')),
                ('reply_text', models.TextField(blank=True)),
                ('reply_voice_file', models.FileField(blank=True, null=True, upload_to='skyvoice/reply/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skyvoice_letters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
